### ISSUE TITLE
Improvements on webInterface (tracking)

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/asibot-hmi#1]
The current implementation is a mere copy-paste from the [asibot-main](https://github.com/roboticslab-uc3m/asibot-main) repo, tweaked to open a `CartesianControlClient` device (from [kinematics-dynamics](https://github.com/roboticslab-uc3m/kinematics-dynamics/)). Future work will involve an exhaustive review of both C++ and HTML/JS code as a start. The main goals are listed below:

- [ ] (*Program* tab) cannot compile on-screen code, must save it first
- [ ] (*Program* tab) compiler chokes on certain characters, e.g. it's unable to recognize `+`, `%` and acute vowels (`á`, `é`...)
- [ ] update Python scripts to use new kinematics-dynamics interface
- [ ] parameterize input/output ports to be loaded via CL/.ini
- [x] provide access to the `ICartesianControl` interface w/ real robot
- [ ] rework *Speech* tab, prevent from reloading page
- [ ] load resources locally by default, don't pull them from robots.uc3m.es
- [ ] write JS-free fallback for webInterface (or state anywhere that JS is required)
- [ ] JavaScript connection interface makes little sense in *Launcher* tab
- [ ] serialize options on HTML load, call them from JS inline scripts, perform checks
- [ ] embrace jQuery?
- [ ] investigate [`yarp::os::` free functions](http://www.yarp.it/namespaceyarp_1_1os.html): portable `mkdir` commands and such 
...
